# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python
    sudo apt-get install -y vim
  SHELL

  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "webservers" => ["default"],
      "dev_enviroment" => ["default"]
    }
    ansible.playbook = "lamp.yml"
  end

  config.vm.synced_folder "../../", "/var/www/trackdrop"
end
