<?php
/*
 * WARNING: DO NOT EDIT UNLESS YOU ARE MAKING TEMPORARY CHANGES
 * THIS FILE IS AUTOGENERATED BY DEPLOMENT SCRIPTS
 */
define('APP_ROOT', '/var/www/trackdrop');

$config['db_host'] = 'localhost';
$config['db_name'] = 'trackdrop';
$config['db_user'] = 'trackdrop';
$config['db_password'] = '{{ dbpwd.stdout }}';
$config['db_port'] = '3306';
?>
